revert whitespacing2

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -14,14 +14,15 @@ RUN \
     export BASE_URL="https://github.com/balena-os/wifi-connect/releases" &&\    
     DETECTED_ARCH=$(uname -m) &&\
     case $DETECTED_ARCH in \
-    "aarch64") \
-    BINARY_ARCH_NAME="aarch64-unknown-linux-gnu" ;; \
-    "x86_64") \
-    BINARY_ARCH_NAME="x86_64-unknown-linux-gnu" ;;\
-    "armv7l") \
-    BINARY_ARCH_NAME="armv7-unknown-linux-gnueabihf" ;;\
-    *) \
-    echo >&2 "error: unsupported architecture ($DETECTED_ARCH)"; exit 1 ;; \ 
+        "aarch64") \
+            BINARY_ARCH_NAME="aarch64-unknown-linux-gnu" ;; \
+        "x86_64") \
+            BINARY_ARCH_NAME="x86_64-unknown-linux-gnu" ;;\
+        "armv7l") \
+            BINARY_ARCH_NAME="armv7-unknown-linux-gnueabihf" ;;\
+        *) \
+            echo >&2 "error: unsupported architecture ($DETECTED_ARCH)";
+exit 1 ;; \ 
     esac;\
     if [ ${VERSION} = "latest" ]; then \
         export URL_PARTIAL="latest/download" ; \
